version: "3.9"
services:
  pritunl:
    build:
      context: .
      args:
        # master was broken when I last tried
        PTZTAG: "1.0.2250.3"
        MONGO_URI: "mongodb://mongo:27017/pritunl-zero"
    depends_on:
      - 'mongo'
    container_name: pritunl-zero
    hostname: pritunl-zero
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
  bastion:
    build:
      context: bastion/.
    depends_on:
      - pritunl
    container_name: pritunl-bastion
  mongo:
    image: mongo:latest
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=pritunl-zero
    volumes:
      - mongo_data:/data/db
    network_mode: bridge

volumes:
  mongo_data:
